# Generated by Django 4.2 on 2023-05-25 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sequence',
            field=models.ImageField(default=0, upload_to='film_sequence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to='actors_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
